language: java
sudo: false
install: true

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "nroduit-github"
    token:
      secure: "5f5c425f2e2dd100f15fd48f66e29271fe7fcfb1"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
